INSERT INTO DOCUMENT_INFO (ID, DOC_NAME, DOC_TYPE, DOC_STATUS) VALUES (11, 'Passport TEST', 'Identification Document', 'SUBMITTED');
INSERT INTO DOCUMENT_INFO (ID, DOC_NAME, DOC_TYPE, DOC_STATUS) VALUES (12, 'Phone Bill TEST', 'Residential Address Document', 'PENDING');
INSERT INTO DOCUMENT_INFO (ID, DOC_NAME, DOC_TYPE, DOC_STATUS) VALUES (13, 'IRAS Notice of Assessment TEST', 'Tax Declaration Document', 'PENDING');
INSERT INTO DOCUMENT_INFO (ID, DOC_NAME, DOC_TYPE, DOC_STATUS) VALUES (14, 'Birth Certificate TEST', 'Identification Document', 'SUBMITTED');
INSERT INTO DOCUMENT_INFO (ID, DOC_NAME, DOC_TYPE, DOC_STATUS) VALUES (15, 'Social Security TEST', 'Insurance Document', 'CANCELLED');